<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_zopim"
 *
 * Auto generated by Extension Builder 2016-11-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Zopim Chat',
    'description' => 'Live chat is the fastest way to engage your customers. Talk to your customers in real-time using Zopim chat. 

 * CONNECT WITH YOUR CUSTOMERS

 * INCREASE YOUR SALES
 
 * PROVIDE PERSONALIZED SERVICE

Only in Zopim.

Zopim is now called Zendesk Chat
and can be integrated into your TYPO3 website now. ',
    'category' => 'plugin',
    'author' => 'Anu Bhuvanendran Nair',
    'author_email' => 'anu.bn@pitsolutions.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-8.3.x',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);